In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [2]:
CapstoneD = pd.read_csv("capstone 2.csv")

In [3]:
CapstoneD.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1.0,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34.0,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2.0,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45.0,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2.0,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
CapstoneD.iloc[:,18:]

      MonthlyCharges TotalCharges Churn
0              29.85        29.85    No
1              56.95       1889.5    No
2              53.85       108.15   Yes
3              42.30      1840.75    No
4              70.70       151.65   Yes
...              ...          ...   ...
7041           74.40        306.6   Yes
7042          105.65       6844.5    No
7043           49.55        475.7    No
7044           69.20      4872.35    No
7045           20.75       418.25    No

[7046 rows x 3 columns]

In [8]:
CapstoneD["TotalCharges"]+ CapstoneD["Churn"]

0         29.85No
1        1889.5No
2       108.15Yes
3       1840.75No
4       151.65Yes
          ...
7041     306.6Yes
7042     6844.5No
7043      475.7No
7044    4872.35No
7045     418.25No
Length: 7046, dtype: object